### ISSUE TITLE
2020.08.29(토) 오후 미팅 로그

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#1]
# 2020.08.29 오후 MEETING

## MEETING 목적 🚩

- [x] 프로젝트 기간 설정
- [x] 주제 정하기
- [ ] 기능 정하기

### 프로젝트 기간 

- 20.08.29~20.09.25

### 역할분담

- Front: 곽병선, 조성원
- Back : 이연주, 하태린

### 프로젝트 주제 브레인 스토밍

- 사이렌오더
- 카페 도매사이트
- 멀캠 커뮤니티
- 축구 팀매칭
- 카페 사장님들의 당근마켓
- 인방 커뮤니티(트위치, 아프리카, 유튜브 통합)

### 주제 선정

카페 사장님들의 당근마켓

- 장점
  - 확장성이 좋다
  - 확실한 메리트 : 트렌드를 읽기 좋음, 편리성 등
- 주제 명확하게 정하기
  - 아이디어스처럼 카페 도매 플랫폼
  - 근처 중고 물품 거래하기
  - 커뮤니티 기능

### 기능 정하기

- 전체기능
  - 결제방식
  - 배포
  - 리뷰
  - 결제
- 프론트
  - CI붙이기
  - 이미 있는 기능 정리하기 -> 리팩토링
  - 배포하기
- 백
  - 회원가입 auth
  - API 명세서 작성
  - DB설계
  - 기술 스택 정하기

### 적용할 사항들

- RDS사용하기
- restful API
- docker/kubernetes 적용하기
- gitflow 적용하기
- github wiki 사용하기 [참고](https://github.com/connect-foundation/2019-02/wiki)
- [깃헙 관리 예](https://github.com/connect-foundation/2019-02)
- 반응형
- 상품등록
- 상품상세
- 채팅
- 채팅관리

### BM

- 도매 업체 및 디저트 가게 광고 수익

## MEETING 결과 📌

- 다른 팀플젝 사례 찾아보기(서비스 배포를 하기전에 어떤걸 했는지)
- 와이어 프레임 작성하기

**Comment by Joylish** [comment]
확인~~~정리 고마웡 태린 짱이당
