### ISSUE TITLE
[Scrum] 20.09.08(화)

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#12]
### 1 ) 함께 할 것 👨‍👨‍👧‍👧

```
10:00 - 10:15 / 데일리 스크럼
```

#### 곽병선

- 기존 코드 다시 파악하기
- 마이 페이지 여러가지 홈페이지 돌며 어떻게 구성할지 감 잡기
- mobx 다시 감 잡기

#### 조성원

- 기존 코드 다시 파악하기
- 주문내역 페이지들 보며 어떻게 구성할지 감 잡기
- mobx 다시 공부하기

#### 이연주

- Spring initializr 의미 정리
- DB 정하기
  - 장단점 정리하기 (maria, cassandra, mongo, redis)
- jar/war 차이점
- 세션 및 인증 구현방법 찾아보기, 정리하기 +)annotation

#### 하태린

- Spring initializr 의미 정리
- DB 정하기
  - 특징 및 장단점 정리하기 (mysql, 카산드라, mongo, redis)
- jar/war 차이점
- 세션 및 인증 구현방법 찾아보기, 정리하기 +)annotation

**Comment by Joylish** [comment]
오늘 일찍 끝났네용 ㅎㅎ 잘 정리해서 내일 얘기해봐요오 태린쓰!

**Comment by kwak-bs** [comment]
다시 리액트 감잡고 시작해봐야겠어여ㅎㅎ!

**Comment by JSWww** [comment]
오늘 하루도 고생하셨어요!! mobx 공부 열심히 해야겠네요 ㅎㅎ
