### ISSUE TITLE
[Scrum] 20.09.09 (수)

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#13]
#### 곽병선

- 기존 코드 다시 파악하기
- 마이 페이지 여러가지 홈페이지 돌며 어떻게 구성할지 감 잡기
- mobx 다시 감 잡기

#### 이연주

- Spring initializr 의미 정리
- jar/war 차이점
- DBMS 조사
- 세션 및 인증 구현방법 찾아보기, 정리하기 +)annotation

#### 조성원

- 기존 코드 다시 파악하기
- mobx 다시 공부하기

#### 하태린

- DB 정하기
  - 특징 및 장단점 정리하기 (mysql, 카산드라, mongo, redis)
- jar/war 차이점
- 세션 및 인증 구현방법 찾아보기, 정리하기 +)annotation

### 1 ) 함께 할 것 👨‍👨‍👧‍👧

```
10:00 - 10:15 / 데일리 스크럼
10:15 - 10:30 / 팀별회의
```

#### 곽병선

- 마이페이지 정하기
- MobX로 마이페이지 만든 블로그 찾아보기

#### 이연주

- 조사한거 이슈 올리기
- MSA설계 고민해보기
  - +) 설계하면서 모르는점 질문으로 정리하기

#### 조성원

- 쇼핑몰 주문내역 찾아보기
- 필요한 기능 정리하기

#### 하태린

- 조사한거 이슈 올리기
- MSA설계 고민해보기
  - +) 설계하면서 모르는점 질문으로 정리하기

**Comment by kwak-bs** [comment]
저도 곧 마이페이지 기능 및 컨텐츠 정리한거 올릴테니 기대해주세요~~!~!~!

**Comment by Joylish** [comment]
MSA 접목시켜보려고 하는데 낯설어서그런지 어렵네요! 찾아보겟습니다
