### ISSUE TITLE
[Discussion] 20.09.10 (목)  - "마이 페이지 이거 어때!?" 

### ISSUE THREAD

**Issue by kwak-bs** [HappyNewEar/Dessert101#14]
#  제안서 🌙

## 1 ) 제안할 내용 👨‍👨‍👧‍👧

- **마이 페이지를 이렇게 목업해봤습니다.!**<br/><br/>

  ![캡처](https://user-images.githubusercontent.com/51367622/92619686-ce987600-f2fc-11ea-9d6c-fa7f7e105dac.PNG)

- **위 사진은 대략적인 마이 페이지의 모습을 나타낸 것입니다. 절대로 완성본이 아닙니다. <br/>일단 최소 기능만 넣어봤습니다.**

## 2 )  그래서 제안하는것은?😎

- **제가 목업한 마이 페이지를 바탕으로 회의를 진행했으면 합니다!**

## 3 ) 회의때 했으면 하는 내용 🔥

- **우리 프로젝트 주제에 맞는 기능적인 요소에 대해 이야기 했으면 좋겠습니다.**

- **마이 페이지는 실질적으로 구매자 입장인데 판매자 입장의 마이 페이지는 어떤 식으로 만들면 좋을지 이야기 하면 좋을 것 같습니다.**

   

## 4 ) 참고 💌

- 무신사 마이페이지<br/>![KakaoTalk_20200909_233747545](https://user-images.githubusercontent.com/51367622/92621245-8e39f780-f2fe-11ea-8c31-3d5c56442d25.png)

- 쿠팡 마이페이지<br/>![KakaoTalk_20200909_233719967](https://user-images.githubusercontent.com/51367622/92621264-95610580-f2fe-11ea-9d93-1a0be5be8a17.png)

**Comment by Joylish** [comment]
구현할 기능 목록 정리한 게 제가 찾을 수 없어서용!
그럼 이번 남은 2.4주간 마이페이지에서 구현할 기능은 다음과 같은건가요?
1. 나의쇼핑
- 주문내역/배송조회
- 취소/교환/.. 조회

2. 나의활동 
- 1대1 문의하기
- 문의내역확인

3. 나의정보
- 개인정보 수정
- 배송지관리

**Comment by kwak-bs** [comment]
기능 구현 설명이 좀 부족한거 같네요. 다시 확실히 구현할 수 있는 기능 scope 정해서 다시 이슈에 올리도록 하겠습니다.

**Comment by hataerin** [comment]
이슈 새로 안파고 수정 or 댓글로 첨부하셔도 될거같아요!
