### ISSUE TITLE
주문내역 페이지 조사

### ISSUE THREAD

**Issue by JSWww** [HappyNewEar/Dessert101#15]
# 주문내역 페이지 조사😄

### 1. cafe24 주문내역 페이지

![cafe24주문내역](https://user-images.githubusercontent.com/9590693/92718233-8335a480-f39c-11ea-9fb1-0e9e7db21822.PNG)

### 2. 옥션 주문내역 페이지

![옥션주문내역](https://user-images.githubusercontent.com/9590693/92718252-86c92b80-f39c-11ea-8d99-90e3a0c9809e.PNG)

cafe24에서 제공하는 기본 쇼핑몰 주문내역 페이지와 옥션의 주문내역 페이지입니다. 위의 두 사진을 참고하여 공통적인 기능을 뽑아 주문내역 페이지를 구성하면 될 것 같습니다😝😝

## 2) 의논할 내용👨‍👨‍👧‍👦

주문내역 페이지를 들어가기 위해선 장바구니에 담긴 목록들을 결제해야 합니다. 그러기 위해선 결제하기 버튼을 눌러 결제 페이지로 들어가야 합니다. 우선 결제 페이지를 건너뛰고 주문내역 페이지를 만들지 의논하고 싶습니다🤔🤔

**Comment by hataerin** [comment]
-날짜별 주문확인
-전체 주문내역 확인

을 우선순위로 구현하시는군요!

**Comment by Joylish** [comment]
오케오케 확인했습니다 전체주문내역에 대한 컴포넌트 설계가 어떻게 되는지 다음 스크럼에서 말씀해주시면 좋을거같아요 ㅎㅎ

**Comment by JSWww** [comment]
네 다음회의까지 한 번 컴포넌트 설계 해보겠습니다!
