### ISSUE TITLE
 Dessert101의 일정 및 개발범위에 관한 제안

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#17]
# Dessert101의 일정 및 개발범위에 관한 제안

>  **왜?** 최종프로젝트, 백엔드 세미프로젝트를 고려하여 일정관리 및 개발범위 설정이 필요하다고 생각하기 때문!

#### ❗ 고려사항

- 최종 프로젝트 **기획서 작성**이 10/9 까지 **과제**로 제출 예정
- 기획서를 바탕으로 **멘토** 역량에 맞게 1~2명 **배정** 
  - 원하는 멘토가 있다면 멘토에 특화된 기술을 기획서에 넣어야겠죵?
  - 주제는 멘티가 선택! 3차 멘토링때 기획서 작성 방안에 대해 멘토링 예정 + 팀별회의 시간 배정
- **평가3** 백엔드 프로젝트는 최종 프로젝트와 별개로 진행 예정
- 서비스 설계와 DevOps 구축 (10/16~10/28)  **+) 평가4**

#### ❗ [9/11 ~ 10/9] 일정안에 해야하는 것

- Dessert101 완성하기 

- 최종 프로젝트 기획서 작성

- 세미프로젝트3 (10/5~10/15)

  

## 나의 의견 😎

- 세미프로젝트 시작 전까지 Dessert101 완성하기 (~9/30)
- 최종플젝으로는 다양한 산업분야를 고려한 주제였으면 해요! +) 더불어 더욱 탄탄한 기획이었으면 합니다ㅎㅎ
- Dessert101과 기획서 작성 병행하기
- 개발범위 설정하기
  - BackEnd
    - MSA적용은 무리라고 생각!
    - Spring Boot까지만 사용해서 기능 완성하기
    - DBMS, 담당기능 정하기
  - FrontEnd
    - Happy New Ear 포크해와서 고도화는 어떨지??
    - 회의후 결과 알려주세용!

## 레퍼런스 📚

> 일정참고
![image](https://user-images.githubusercontent.com/26705587/92872240-c3e6f980-f440-11ea-8d8a-77c79f014817.png)
![image](https://user-images.githubusercontent.com/26705587/92872285-cfd2bb80-f440-11ea-96e0-5549a1c488ee.png)
> 최종플젝 주제선정시 참고
![image](https://user-images.githubusercontent.com/26705587/92872784-55ef0200-f441-11ea-8dbb-b4fcb472e53e.png)

**Comment by soyoung-Jung** [comment]
백엔드 세미 프로젝트가 어떤 방향과 어떤 팀으로 하게 될 지 모르겠지만, 만약에 백엔드 세미프로젝트가 이 팀으로 진행되면 Dessert101을 연장선으로 해도 괜찮을 것 같아요..! 파이널때 새로운 주제로 하는 것은 저도 찬성합니당 이따 회의 때 이야기해보아요~!

**Comment by kwak-bs** [comment]
세미 프로젝트3이 어떤식으로 갈지는 모르겠지만 만약에 따로 주제가 없거나 팀원도 변동이 없으면 Dessert101을 세미 프로젝트3의 연장선으로 진행해도 괜찮을 것 같아요. 그리고 파이널 프로젝트는 멘토님과의 회의를 통해서 나중에 결정해도 무리가 없을것 같아요. 
일단 FE 쪽은 10/9일까지 리액트 감도 다시 잡을겸 본인이 맡은 페이지 및 기능에 대해서 구현하는 것이 목표고 예상외로 빠르게 진행된다면 고도화 하는 진행도 생각해보겠습니다!! 
가능한 날짜까지 구체적으로 진행할 수 있는 개발범위 제안!!! 아주 좋은 것 같아요 ㅎㅎ 잘 봤습니다.  자세한 내용은 오늘 스크럼때 말해봅시다 ㅎㅎ

**Comment by Joylish** [comment]
저는 조금 다른 의견을 제시하고 싶습니다. 따라서 파이널때 가서 MSA 설계를 하고 직접 적용하기에는 처음 시도해보는 거라 시행착오가 많지 않을까 싶습니다. 물론 파이널 때 멘토님이 MSA 아키텍쳐 설계를 도와주시겠지만 도움이 한정적일거라고 생각합니다. 그리고 현재까지 수업에서 스프링부트를 다루지 않았고, 다음주부터 스프링부트 부분이 진행되기 때문에 그때까지 백엔드 팀은 MSA 설계를 하고 스프링부트를 프로젝트를 만들고 천천히 적용시켜보면 어떨까요? 요약하자면, 시간 상 부족하다해서 모놀리식으로 진행하기 보다는 파이널 프로젝트를 위해 이번 프로젝트에서 백엔드 팀은 개발 범위를 줄여 MSA 설계를 진행하고 적용하여 개발하면 좋을 것 같습니다.

**Comment by JSWww** [comment]
최종플젝 주제를 다양한 산업분야를 고려했으면 좋겠다는 것에 동의합니다!
