### ISSUE TITLE
MSA 아키텍쳐 설계를 위한 MSA 아키텍쳐 정의 제안

### ISSUE THREAD

**Issue by Joylish** [HappyNewEar/Dessert101#18]
# MSA 아키텍쳐 설계를 위한 MSA 아키텍쳐 정의 제안

## 이슈 ❗️
-  MSA 아키텍쳐 설계를 위해 공통적인 서비스를 담당하는 기능끼리 묶어 하나의 도메인으로 분리해야 합니다. 

![image](https://user-images.githubusercontent.com/52230415/92901708-a5422c00-f45b-11ea-956c-405d05ef4fdc.png)

MSA 아키텍쳐 정의 시 거쳐야하는 과정을 7단계로 나누어 보았습니다.

#### 1. 시스템 작업 식별
- 시스템 작업을 기술하기 위해 필요한 voca를 제공하는 핵심 클래스로구성된 고수준의 도메인 모델 생성

#### 2. 시스템 작업 식별 후 그 동작을 도메인 모델 관점에서 기술
 - 고수준 도메인 모델 생성 (스토리에 포함된 명사 분석)

>
>Given
>소비자가 있다
>음식이 있다
>음식점은 소비자의 주소로 제시간에 음식을 배달할 수 있다
>주문 총액이 음식점의 최소주문량 조건에 부합한다
>
>When
>소비자가 음식점에 음식을 주문한다
>
>Then
>소비가 신용카드가 승인된다
>주문이 PENDING_ACCEPTANCE 상태로 생성된다
>생성된 주문이 소비자와 연관된다
>생성된 주문이 음식점과 연관된다.
>
>스토리에서 추출할 수 있는 명사는 Consumer, Order, Restaurant, CreditCard 등이다.
>그리고 아래처럼 정의할 수 있다.
>
>Consumer - ~을 주문한다 - Order - ~에 대한 - Restaurant
>

#### 3. 시스템 작업 정의
크게 두가지 CUD(생성, 수정, 삭제)와 R(읽기)로 나눈다.

#### 4. 시스템 커맨드 정의
시스템 커맨드는 다음의 구성요소로 정의된다.

* Actor : 누구의 작업인지
* Story : 어떤 스토리인지
* Command : 어떤 커맨드인지, 예를들어 게시글 생성이라면 createBoard()
* Comment : 설명

커맨드는 또한 다음과 같이 자세하게 정의된다

* 작업 : createBoard(사용자 ID, 게시글 제목, 게시글 본문)
* 반환값 : Board 식별자
* 선행 조건 : 로그인이 되어있어야한다
* 후행 조건 : 게시글이 공개상태로 생성된다

#### 5. 서비스 정의 (분해)

서비스 분해 패턴은 크게 두가지로 나눌 수 있다.

1) DDD 개념 기반
**DDD 하위 도메인 별로 서비스를 정의한다**
- ubiquitous lanauge(공용 언어)
- sub-domain(하위 도메인)
- bounded context(경계 컨텍스트)

2) 비즈니스 능력 기반
**비즈니스 능력에 따라 서비스를 정의한다**

예시) 배달의 민족
>공급자 관리
> 배달원 관리 : 배달 정보 관리
> 음식점 정보 관리 : 음식점 메뉴, 위치, 영업 시간, 기타 정보 관리
> 소비자 관리 : 소비자에 관한 정보 관리
>
> 주문 접수 및 이행
> 주문 관리 : 소비자가 주문을 생성/관리할 수 있도록 함
> 음식점 주문 관리 : 음식점의 주문 준비 상태를 관리
>
> 실행 계획(logistics)
> 배달원 가용성 관리 : 배달원이 배달 가능한지 실시간 관리
> 배달 관리 : 주문을 소비자에게 배달
>
> 회계
> 소비자 회계 : 소비가 과금 관리
> 음식점 회계 : 음식점 지불 관리
> 배달원 회계 : 배달원 지불 관리

#### 6. 서비스 분해 장애요소 정의
* 네트워크 지연
서비스간 왕복 횟수를 줄일 수 있도록 배치 API를 구현하거나 비싼 IPC를 이용한다
* 동기 통신으로 인한 가용성 저하
비동기 메시징을 이용해 느슨한 결합으로 가용성을 높이는 것이 좋다
* 여러 서비스에 걸쳐 데이터 일관성 유지
사가라는 방식으로 트랜잭션을 관리한다
* 데이터의 일관된 뷰 확보
분해를 저해하는 만능 클래스
만능 클래스를 만들지 말자. MSA에서는 어느정도의 중복은 허용한다.

#### 7. 서비스 API 정의
시스템 작업을 서비스 배정하고 서비스 간 협동 지원에 필요한 API 결정합니다.

## 나의 의견 😎

- MSA 설계시 시스템 작업 정의, 서비스 분해가 전제되어야 한다고 생각합니다. 이번 프로젝트에 MSA 적용시 백엔드팀은 다음과 같은 작업 후에 각자 맡은 서비스 API와 관련된 DB 설계 및 API 구현을 하면 좋을 것 같습니다.

## 관련된 이슈 📎

> 관련 이슈 없음

- issue title (#issue number)

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by soyoung-Jung** [comment]
음 일단 중요한 건 이번 프로젝트를 msa를 적용해서 구현을 할것인지를 정하는 것 같아요..! 그런데 msa를 적용하게 되면 세미프로젝트 전까지의 시간이 20일 정도인데, 그전까지 msa를 설계하고 개발을 진행해서 마무리할 수 있을까하는 걱정은 됩니다. 세미프로젝트의 진행에 대해서 내일 매니저님께 제가 한번 여쭤보는건 어떨까요?

**Comment by soyoung-Jung** [comment]
다시 생각해보니, 저희가 지금 프로젝트를 msa를 적용해서 해도 괜찮을 거 같은게, 모놀리식으로 프로젝트 진행하는 경험은 세미프로젝트 기간에도 충분히 할수있을 것 같아요! 세미 하기 전까지는 msa를 공부하면서 전반적인 흐름을 잡았으면 좋겠습니다..! 그리고 이 프로젝트를 스프링 부트로 할텐데 msa를 공부하는 동안 수업진도를 따라 스프링 부트를 공부한 뒤에 개발을 하면 두마리 토끼를 잡을 수 있다고 생각합니다! 

참고로, msa를 공부할 수 있는 k-mooc 강좌 링크 알려드려요! 저희 과정 멘토님 중 한분께서 찍으신 거랍니당

http://www.kmooc.kr/courses/course-v1:KAISTk+2018_K14+2020_K14_02/about

**Comment by hataerin** [comment]
MSA설계가 막연했는데 이렇게 단계별로 정리해주셔서 조금 이해가 가네요! 감사합니당ㅎㅎ

**Comment by JSWww** [comment]
시간도 많이 없는데 조사 많이 하셨네요 ㄷㄷ 고생하셨어요!!👍👍

**Comment by kwak-bs** [comment]
정리가 정말 잘 되어있군요. 고생했습니다 ㅎㅎ
