### ISSUE TITLE
Dessert101의 구현 기능 수정 제안

### ISSUE THREAD

**Issue by kwak-bs** [HappyNewEar/Dessert101#19]
# Dessert101 구현 기능 수정 제안 

> **왜?** (이 제안을 한 이유!) 성원이가 만드는 주문내역 페이지와 마이 페이지의 기능이 겹치는 부분이 많아서 제안해봅니다!  

<br/><br/>

## 나의 의견 😎

- 페이지 구성을 성원이한테 맡기고, 저는 검색 기능(검색어 추천 기능)을 구현하고자 합니다. 
- 일단, 전체 개발 속도를 고려했을 때 파이널 프로젝트를 위한 개인의 개발 역량을 향상 시키는 것이 더 중요하다고 판단됩니다. 그래서 FE는 파이어베이스와의 연동을 통한 비동기 처리 방법 공부하고자 합니다. 
  - async- await, promise
-  throttle과 debounce 함수 공부 
- lazy loading 공부 

## 구현할 기능 😎

1. **검색어 추천 (필수)**
  - 인풋넣으면 관련 추천검색어 밑에 뜨게하기

2. **검색 (필수)**
  - 엔터치면 관련 데이터 카드로 보여주기

3. **검색어 추천 - 사용성 개선**
  - 키보드와 마우스를 이용해서 추천 검색어를 선택할 수 있게 만들기.
  - 추천 검색어가 로딩되는 중임을 알리는 UI적 처리하기.

4. **검색 - 사용성 개선**
  - 검색 중 에러가 발생한 경우, 에러가 발생했다는 것을 알리는 UI적 처리를 하기.
  - 검색 결과가 로딩되는 중임을 알리는 UI적 처리를 하기
  - 검색이 일어나면 라우터 처리 후, url 뒤에 `?q={검색어}`를 붙입니다. 

5. **퍼포먼스 향상**
  - 검색어별 추천 검색어를 로컬에 캐싱해서 사용하도록 합니다.
  - 추천 검색어 API 호출 중 새로운 검색어 입력이 감지되면 기존의 ajax 요청을 취소하고 새로운 검색어를 기준으로 API 요청을 보내기 
  - Debounce를 구현합니다. 이를 통해 검색어가 입력될 때마다 서버에 요청이 일어나지 않게 한다. 
  - 키워드별 검색 결과를 캐싱하여 사용한다. 단, 캐싱된 데이터는 브라우저를 닫으면 사라져야 한다.

**Comment by soyoung-Jung** [comment]
추천검색어 기능은 필수적인 것 같아요! ㅎㅎ 꼭 구현한 모습 보고싶습니다~

**Comment by Joylish** [comment]
오 디테일해서 좋네요 기대됩니다 ^-^

**Comment by JSWww** [comment]
개인 역량을 향상시켜야 한다는 것에 동의합니당!

**Comment by hataerin** [comment]
퍼포먼스 향상하는거 좋은거같아요!! 다음플젝에도 유용하게 쓰일것 같네용!!ㅎㅎ
