### ISSUE TITLE
2020.09.11 오후 마지막 MEETING😥인줄 알았지만 아니었지롱!

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#20]
# 2020.09.11 오후 마지막 MEETING😥 인줄 알았지만 아니었지롱!

## MEETING 목적 🚩

- 프로젝트 마무리

## MEETING 내용 ✍️
- 이번 프로젝트는 애자일, 스크럼 방법론을 적용 및 공부하는데 목적을 두었습니다.
- 팀 프로젝트 때 발생할 수 있는 이슈를 관리해보았습니다.
- 서비스 기획을 하며 사용자 스토리 및 요구사항, 에픽 등을 정리해보는 경험을 해보았습니다. 

## MEETING 결과 📌

- 그동안 Dessert101을 사랑해주셔서 감사합니다❤
- 🎊뽀짝팀의 다음 프로젝트의 밑거름이 될 수 있는 좋은 경험이었습니다🎉
- 1일 1 TIL이상 작성하기
- 업로드 기간: 팀회의 끝나고~ 팀회의 시작전
- 안하면 벌금 천원!
- README.md 작성하기

**Comment by soyoung-Jung** [comment]
확인했습니다~! 다음 프로젝트로 잘 달려보아요:))

**Comment by kwak-bs** [comment]
ㅠㅠㅠㅠ아쉬운 마음은 뒤로 하고 시즌 3를 잘 구상해봅시다 ㅎㅎ

**Comment by JSWww** [comment]
dessert101의 마지막 미팅이라 아쉽지만 다음 프로젝트를 위한 발판이 된 것 같네여 ㅎㅎ 고생하셨어요~~
