### ISSUE TITLE
차별화된 Dessert101을 위한 아이디어/기능 제안

### ISSUE THREAD

**Issue by soyoung-Jung** [HappyNewEar/Dessert101#22]
# 차별화된 Dessert101을 위한 아이디어/기능 제안

- 기존 Dessert101에 대한 멘토님들의 의견에 따라 차별화 전략이 필요하다.

## 이슈 ❗️

- 참고모델 아이디어스의 디저트 주문 방식

  - 디저트의 옵션이 제한적이다. (단순 수량, 한정된 맛 선택 등)

    :arrow_right: 소비자가 커스터마이징 할 수 있도록 하자!

  - 디저트의 원재료 등 정보제공이 미비하다.

    :arrow_right: 원재료의 정보를 확실히 공개할 뿐 아니라 판매자의 레시피를 공유/판매할 수 있도록 하자!

## 나의 의견 😎

- **커스터마이징이 가능한 디저트**

  소비자, 즉 카페 사장님은 자신의 카페 컨셉에 맞는 디저트를 원할 수 있다. 소비자가 원하는 디저트를 공급받기 위한 방법을 모색해보았다.

  1. *옵션의 폭을 넓히자.*

     ex. 밀가루 -> 쌀가루, 우유 -> 두유, 설탕양 조절

  2. *소비자가 아이디어를 제안하여 판매자를 낙찰하는 방식*

     아이디어는 많지만 그것을 구현할 손재주가 없는 소비자를 위한 기능.  소비자의 아이디어를 제시하면, 판매자들이 그것을 구현해낼 수 있도록 하는 장을 만들어보자.

- **레시피 공유 및 판매 서비스**

  소비자가 판매자의 상품 구매 후 만족하여 똑같이 만들어 보고 싶은 경우, 판매자의 레시피를 구매할 수 있다. 판매자는 선택적으로 레시피를 판매할 수 있다.

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by Joylish** [comment]
오오!! 제일 먼저 올리셨군요 짱짱👍👍  디저트의 원재료 정보를 투명하게 공개한다는 부분이 정말 좋은 아이디어인거 같아요! 판매하는 디저트 신뢰를 더 높일 수 있을 거 같아요😀 다소 걱정되는 부분은 커스터마이징인 거 같아요 요즘에 디자인적으로 커스텀 레터링 케이크, 롤케이크, 마카롱 등을 판매하는 경우는 많이 봤고 저도 신청해봤습니당! 하지만 재료 부분에서 커스터마이징을 한다면,, 판매자가 밀가루와 쌀가루의 베이킹 방식이 차이가 있어 잘 모를 수 있도 있고 재료양을 조절하는 부분도 해당 재료가 들어가지 않으면 베이킹이 되지 않을 수 있지 않을까하는 생각이 듭니당! 구매자인 카페 사장님 중 디저트 베이킹을 잘 모르는 분들이 재료의 정도를  따로 지정할 수 있을까.. 오히려 선택에 대한 자유도가 높아져 복잡하다라는 생각이 들지 않을까하는 걱정이 살짝 듭니당ㅎㅎ 그래서 감히 의견을 내보자면 판매자인 카페 사장님이나 베이킹을 전문적으로 하시는 개인분들이 디저트 정보를 올리실 때 조금 더 구체적으로 재료를 적도록 하고, 우리 서비스에서는 재료 관련 필터링 기능을 제공해서 구매자들 각자가 자신의 카페에서 팔고 싶은 디저트를 찾을 수 있게하면 어떨까용??

**Comment by kwak-bs** [comment]
오 아이디어 굉장히 좋은거 같아요 ㅎㅎ 다만 걱정되는 부분이 있다면,,,  레시피 공유 및 판매 서비스 부분입니다. 우리의 의도대로 잘 이루어 질지 모르겠어요.ㅠ 레시피 자체 저작권은 판매자에게 있는데, 한 구매자가 구매를 하고 그 레시피를 그대로 다른 잠재 구매자들에게 더 비싼 값으로 판매를 하거나, 아니면 모르쇠로 자기 유투버에 올리는 악용이 이루어 질 수도 있을것 같아요...! 요즘 같은 시대는 레시피 자체가 워낙 자유 자재로 공유가 되는 시대라,, (ex, 백종원) 만약 이 기능을 구현하게 된다면, 조금 더 회의를 통해 구체화를 시키고 해보는게 좋을것 같습니당 ㅎㅎ 감히 의견 올려봤습니다 ㅎㅎㅎㅎㅎ 아이디어 잘 봤어요!

**Comment by JSWww** [comment]
디저트의 원재료 정보제공은 정말 좋은 아이디어인 것 같습니다! 저도 아이디어스의 수제 먹거리들을 보면서 어떠한 재료들이 들어갔는지 궁금했었습니다.

레시피 공유 및 판매 서비스같은 경우는 아이디어스에서 금손 클래스라는 명칭으로 온/오프라인에서 레시피를 원작자에게 돈을 지불하고 배우는 형식으로 되어 있는데 비슷하게 하면 어떨까 싶네요😁

**Comment by hataerin** [comment]
아이디어 좋은거같아용!! 아예 베지테리언을 위한 카테고리같은걸 따로 둬도 좋을것 같네용!! 
그리고 상품 전체목록 화면에서 조그맣게 할랄/비건 등 뱃지를 달아놓으면 소비자들이 상세페이지 들어가지 않아도 정보를 받을 수 있을것 같아서 좋을 것 같아요ㅎㅎ
![image](https://user-images.githubusercontent.com/26705587/93707431-7584d980-fb69-11ea-88a1-0cddb7977efd.png)
