### ISSUE TITLE
차별화된 Desert101을 위한 아이디어/기능 제안

### ISSUE THREAD

**Issue by kwak-bs** [HappyNewEar/Dessert101#23]
# 내 주변에 있는 판매자는 누가 있을까?

- ***왜?*** 기존 Dessert101에 대한 멘토님들의 의견에 따라 차별화 전략이 필요하기 때문!

## 이슈 ❗️

- 내 주변에 있는 판매자들에게 직접 가서 먹어보고 싶다!

  - ***왜 이런 이슈를?*** 배달에 걸리는 소요시간이 길어질 경우 음식이 식거나 본연의 맛을 느끼지 못할 수도 있다. 

    ✔  내 주변에 있는 판매자의 위치를 한 눈에 알아볼 수 있게하자!

## 나의 의견 😎

- **지도 API를 활용한 내 주변 판매자의 위치 제공 서비스**

  1. *판매자, 고객은 본인의 위치를 등록할 수 있도록 한다.*

     -  선택적 등록 가능. (단, 판매자는 필수)

     

  2. *지도 API를 제공하여 고객은 본인 위치를 기준으로 1~5KM 떨어진 판매자의 위치를 확인할 수 있다.*

     - 대한민국 지도 API -> 내 주변 판매자 확인하기 클릭하면 -> 1~5km 떨어진 판매자의 위치를 한 눈에 확인할 수 있도록 한다.

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by soyoung-Jung** [comment]
아이디어스의 경우 생산자 및 소재지가 불분명하거나 그냥 주소로만 되어 있는데, 이런 기능이 있다면 확실히 차별화는 있을 것 같아요. 그리고 만약 제가 소비자 입장에서 저 기능을 사용한다면, 디저트가 식거나 맛이 변할까 우려해서라기 보다는  재고가 소진되어 빠르게 디저트를 공급받아야할 때 필요하다고 생각할 것 같습니다! 
약간 우려되는 점은 저희가 동네기반 서비스에 대해 논의했을 때 기능적인 지도API를 사용하는 것에 대한 어려움이 있을 것 같다고 예상했었는데 같은 맥락에서 구현의 어려움이 있다고 보여지네요! 좋은 아이디어 감사합니다~ 이따 회의 때 보아요.

**Comment by JSWww** [comment]
확실히 내 근처에 계시는 판매자분들이 어떠한 디저트를 팔고 있을지 확인할 수 있다면 재밌을 것 같고 디저트에도 더 관심이 갈 거 같습니다!

**Comment by Joylish** [comment]
오오 재밌는 아이디어인거같아요! 디저트를 공급을 원하는 주위에 있는 카페 사장님들이 직접 가서 눈으로 보고 먹어보고 확인할 수 있으면 구매자와 판매자 간 친밀함을 형성하는 데 도움을 줄 수 있을 거 같아요 ㅎㅎ
