### ISSUE TITLE
차별화된 Desert101을 위한 아이디어/기능 제안 

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#24]
# 차별화된 Desert101을 위한 아이디어/기능 제안

- 기존 Dessert101에 대한 멘토님들의 의견에 따라 차별화 전략이 필요하다.

## 이슈 ❗️

카페는 **공간**을 파는 곳 : 컨셉이 확실해야함
-> 사장님들의 컨셉잡는것을 도와주자!

## 나의 의견 😎

- 다양한 카테고라이징
  - 단순한 식품 종류 뿐만 아니라 연령별, 분위기, 트렌드10 등 다양한 필터 제공
- 식품 보관 및 조리 가이드 폼 제공 
  - 판매자가 목표했던 맛의 100%를 제공하기 위한 보관 및 가이드 폼 제공
  - 예) 보관방법: 냉동보관, 소비기한: 1달, 조리방법: 오븐 180도 15분 조리 
- 데코 예시 사진 제공
  - 디저트는 맛 뿐만 아니라 비주얼도 생명! 
  - 어떻게 데코하는지, 어떤 접시가 적합한지, 추천 사이드(냉동블루베리, 휘핑크림)등  예시 사진 제공

**Comment by Joylish** [comment]
오호호호! 수많은 카페들 중에 디저트 판매자인 자신의 컨셉이 확실해질 수 있다면 정말 좋을 거 같아요 다른 사람과 자신의 차별점을 어필할 수 있을거같아요🥰 제안해주신 연령별은 어떤 디저트를 어떤 연령이 좋아하는지 알려면 기존 데이터를 분석해서 제공해야할 것 같은데.. 다소 걱정이 되는 부분입니당 이따 회의시간에 판매자의 컨셉을 어떤 방식으로 정할 수 있을지 조금 더 디테일한 정보가 있으면 더 좋을 거 같아용!! 회의 때 기대할게용╰(*°▽°*)╯

**Comment by JSWww** [comment]
이슈 확인했습니다. 다양한 카테고라이징은 상품 판매 범위를 디저트로 한정한Dessert101에 특화된 기능일 수 있겠네요!

**Comment by kwak-bs** [comment]
아이디어 좋은 것 같아요! 카페 사장님들도 컨셉을 정할때 좀 더 편리하게 정할 수 있을거같아요!

**Comment by soyoung-Jung** [comment]
카테고라이징을 판매자가 상품 등록 시 해시태그 등으로 분류할 수 있게끔 하면 (아이디어스처럼) 기능 구현을 할 때 많은 공부가 될 수 있을 것 같아요!! 카페는 공간을 파는 곳이라는 말이 와닿는 만큼 컨셉은 확실히 중요한 것 같습니다.
