### ISSUE TITLE
왜 Dessert101을 사용해야하는지에 대한 의견 정리

### ISSUE THREAD

**Issue by JSWww** [HappyNewEar/Dessert101#25]
# 구매자 입장에서 굳이 우리 서비스를 왜 사용해야 할까?

- 우리 서비스를 사용해야만 하는 타당성에 대해 정리해보고자 합니다.

## 이슈 ❗️

우선 기존에 서비스를 운영하고 있는 디저트 관련 사이트를 조사해봤습니다.

### 1. 희소당

- only 디저트 판매 사이트
- 희소당에서 만든 디저트를 개인 카페에 납품
- 현재 카페를 운영중인 사업자에 한하여 회원가입 후 이용 가능 (일반인 이용 불가)
- 샘플패키지를 제공하여 희소당의 여러 디저트를 한번에 평가해 볼 수 있음

### 2. 아이디어스

- 손으로 만든 가치 있는 작품들을 작가들이 직접 등록/판매하는 마켓 플랫폼
- 작가라는 명칭으로 입점 (사업자등록증 있어야 함)
- 수공예 액세서리, 의류, 수제 먹거리까지 총 25만 개 이상의 다양한 카테고리의 작품들을 판매
- 핸드메이드 마켓 플레이스
- 아이디어스 스토어, 아이디어스 크래프트 랩, 온/오프라인 금손클래스(레시피 강의) 운영
- 손으로 직접 만든 핸드메이드/수공예 작품만 판매 가능 (공산품, 사입제품, 외주 공장 생산, DIY KIT 상품 등은 판매 불가)

## 나의 의견 😎

다음은 위 두 사이트와 비교하여 나온 Dessert101의 장점입니다.

- 개인 카페 사업자들도 Dessert101에서 자기만의 디저트 납품 가능
  - 개인 카페 사업자가 온라인 쇼핑몰을 따로 만들지 않아도 Dessert101에서 제공해줌
  - 개인 사업자들의 온라인 쇼핑몰들을 Dessert101으로 모으는 효과
- 카페 사업자뿐만 아니라 일반회원들도 개인 카페 사업자가 등록한 디저트 구매 가능
- 상품 판매 범위를 디저트로 한정하여 아이디어스와는 다르게 개인 카페 사업자 및 디저트 구매자들에게 특화된 서비스 제공

위 두 사이트와 Dessert101의 차이점을 비교해보고 느낀점은 희소당과는 확실히 서비스 차별점이 있지만 아이디어스와 비교했을 시 Dessert101만의 기능은 부족하다고 느꼈습니다. 

상품 범위를 디저트로 좁혀 개인 카페 사업자 및 디저트 구매자들에게 특화된 서비스를 제공하는 만큼 그들을 위한 아이디어스에는 없는 차별되는 기능이 필요하다고 생각됩니다.

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

- [희소당](https://www.heesodang.com/)
- [아이디어스](https://www.idus.com/)

**Comment by Joylish** [comment]
와우 지금까지 나온 회의에서 나온 서비스와 대비하여 정리해주셨네요!!🤩 흐음 이렇게 보니 단순히 현재 디저트를 유통하고 있는 사업자뿐만 아니라 베이킹을 하시는 개인분들이 우리 deseert101을 사용할 수 있다는 장점이 약하다고 보여지네요 ㅜㅜ 혹시 생각하시는 아이디어스에 없는 차별된 기능있으신가용?? 회의시간이 기대되네요!

**Comment by soyoung-Jung** [comment]
이렇게 정리해주시니 파악하기가 너무 좋습니다! 확실히 아이디어스에 아이디어를 떠볼려본 것들이 이미 구현이 되어있는 것이 많더라고요..ㅠㅜ 특화된 장점을 잡게 되면 기획의도 발표시 타 업체들과의 비교를 하며 저희의 강점을 소개하면 좋을 것 같습니다.

**Comment by kwak-bs** [comment]
확실히 우리와 비슷한 컨셉을 가진 두 홈페이지를 비교해주시니 한 눈에 들어오기 편하네요! 감사합니다!

**Comment by hataerin** [comment]
정리를 잘해주셔서 우리 서비스의 차별점을 생각하기 편하네요ㅎㅎㅎ 감사합니다!
