### ISSUE TITLE
차별화된 Desert101을 위한 아이디어/기능 제안

### ISSUE THREAD

**Issue by Joylish** [HappyNewEar/Dessert101#26]
# 차별화된 Desert101을 위한 아이디어/기능 제안

- 우리 서비스의 차별화된 **뽀인트**를 찾아야 함

## 이슈 ❗️

1) 구매자 지역 기준으로 판매되고 있는 디저트 필터링 제공
2) 구매자와 판매자의 직접적인 커뮤니케이션 수단 제공
3) 지역기반으로 판매자와 구매자의 정보 공유의 장 제공

## 나의 의견 😎

1에 대한 의견) 디저트 구매자 근처에 있는 판매자의 디저트를 볼 수 있으면 좋을 것 같습니다. 구매자가 판매자의 상품을 직접 보고 거래를 할 수 있다면 상호신뢰관계 형성하는 데 기여할 수 있을 것이라 생각합니다. 이는 결국 우리 서비스에 대한 충성도와 신뢰도를 고취시킬 수 있습니다. 

2에 대한 의견) 판매자가 공개한 정보는 일방향적인 정보로 구매자가 추가적으로 궁금한 부분을 질문할 수 있으면 좋을 것 같습니다. 또한 채팅 기능을 구현하면서 필요 기술을 공부할 수 있다고 생각합니다. 

3에 대한 의견) 디저트 정보관련 뿐만 아니라 카페를 운영하는 데 도움이 필요할 때 지식in처럼 질문할 수도 있고, 카페 이사로 물품을 나눔을 할 수 있고, 원데이클래스를 열어 카페사장님들끼리 친목을 도모할 수 있는 것 등 실시간 피드를 통해 카페를 운영하고 디저트에 관심이 있는 사람들 간의 공통된 공감대로 서비스가 활성화 될 수 있을 것 같습니다.

## 관련된 이슈 📎

- 내 주변에 있는 판매자는 누가 있을까? (#23 )

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by soyoung-Jung** [comment]
2번과 3번모두 아이디어스에 있는 기능이기는 하지만, 저희가 기술을 구현하는 데에 있어서 배움의 기회가 될 수 있을 것 같아 좋아요! 1번은 병선님도 의견을 내신 만큼 확실히 우릴 dessert101의 강점을 부각시키기에 좋은 것 같습니다!!

**Comment by kwak-bs** [comment]
아이디어 잘 봤습니다. 저도 2번 아이디어는 적극 찬성이에요! 카페 사장님들과의 직접적인 소통은 정말 좋은거같아요 !

**Comment by JSWww** [comment]
이슈 확인했습니당!
