### ISSUE TITLE
UI/UX 설계시 제안

### ISSUE THREAD

**Issue by Joylish** [HappyNewEar/Dessert101#5]
## 이슈 ❗️
* 추후에  UI/UX 디자인 설계가 필요합니다.
* 디자인 툴을 다루기 위해 배우는 시간이 필요합니다.🐤 

## 나의 의견 😎
소규모 팀원으로 사용자 스토리보드 작성, 디자인 설계 단계를 따로 진행하지 않고 한 번에 진행하면 좋지 않을까하는 생각을 했습니다. 기존 디자인 툴을 다루기 위해서 따로 공부가 필요합니다. 노코드 플랫폼 adalo에서는 필수 기능(로그인, 회원가입, 상품목록, 상품상세, 결제, 결제내역, 프로필) 관련 디자인을 기본으로 제공합니다. 또한 zaiper라는 서비스를 활용해서 adalo와 github를 연동할 수 있다는 것을 확인했습니다. github를 최대한 활용하고싶다는 팀원분들의 의견에 잘 맞을거라 생각합니다.이를 활용해서 최종 웹 서비스 디자인을 고려해보면 좋겠습니다. 
![image](https://user-images.githubusercontent.com/52230415/91887422-bce41c80-ecc5-11ea-9dee-61abcde0f1ba.png)
![image](https://user-images.githubusercontent.com/52230415/91887502-d1c0b000-ecc5-11ea-89fb-abea5f3a19cb.png)

## 관련된 이슈 📎
관련 이슈 없음

## 레퍼런스 📚
[노코드 플랫폼](https://www.adalo.com/)
[github와 adalo를 연동해주는 서비스](https://zapier.com/app/dashboard)

**Comment by hataerin** [comment]
디자인할때 참고하면 좋을거같은 사이트 첨부합니당
[카페 디저트 납품업체: 하이푸디](http://www.hifudi.com/)

**Comment by JSWww** [comment]
adalo  한 번 확인해보겠습니다!

**Comment by kwak-bs** [comment]
adalo 정말 좋은 목업 플랫폼인거 같아요! FE 쪽에서 husky & git hooks 관련해서도 더 공부 많이 해볼게요! 이슈로 올릴테니까 기대해주세요!
