### ISSUE TITLE
API 문서 작성시 제안

### ISSUE THREAD

**Issue by Joylish** [HappyNewEar/Dessert101#6]
### 이슈 ❗️
* 프론트엔드와 원활한 커뮤니케이션을 위해 API를 문서화가 필요합니다. 🐤

### 나의 의견 😎
개발할 때, 한 기능을 구현하기 위해 백엔드 담당 팀원과 프론트엔드 담당 팀원들은 API 하나마다 어떤 파라미터 결과값이 전달되는지 등과 같은 이슈로 여러 번 소통을 해야합니다. 구체적인 예로 "어떤 URI 방식으로 데이터를 전달해줘야해?","서버에서 데이터 전송 수신 성공시 프론트에 메시지는 어떻게 전달되는거야?", "서버 에러시 프론트에 어떻게 메시지를 전달하는거야?" 등이 있을 거 같습니다. 빈번한 소통을 지양하자는 건 아니지만 비효율적인 소통은 각 팀원분들께 피곤함을 유발하며 이는 개발 속도를 더디게 할 수 있다는 생각이 들었습니다. 따라서  개발하기 전에 프론트엔드 담당과 백엔드 담당 팀원끼리 소통해서 REST API 설계를 문서화할 필요가 있다고 생각합니다.  

대표적인 API 문서 자동화 툴로 swagger이 있습니다. 어제 회의에서 나온 팀 가명으로 swagger API 문서를 만들어보았습니다. 내용은 관련이 없는 것입니다. 어제 회의 기준으로 백엔드 메인 프레임워크로 spring boot로 의견이 모아지고 있어 spring boot와 swagger 연동방식을 알아보았습니다. spring boot 프로젝트에 swagger dependency를 추가한 후 swagger 관련 어노테이션을 통해 API 문서를 작성할 수 있습니다. 레퍼런스 남겼습니다 확인해주시면 감사하겠습니다 :) 

![image](https://user-images.githubusercontent.com/52230415/91927868-9057f100-ed15-11ea-8ea7-11b9948b3dc3.png)

이외 API 문서화 도구로 gitbook이 있습니다. 관련 내용은 레퍼런스에 남겼습니다. 확인부탁드립니다. 시간되실 때 제가 추가한 레퍼런스 뿐만 아니라 다른 자료도 많으니 봐주셔서 팀원분들꼐 더 익숙한 API 문서화 도구를 선정했으면 합니다!

### 관련된 이슈 📎
* API 문서화 툴을 어떤 것을 사용할 지에 대해 논의해야합니다.

### 레퍼런스 📚
[gitbook 관련 레퍼런스](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-6.-API-%EC%8A%A4%ED%8E%99-%EC%84%A4%EA%B3%84%EC%99%80-%EB%AC%B8%EC%84%9C%ED%99%94-%EB%B0%A9%EC%8B%9D-%EA%B2%B0%EC%A0%95-2)
[gradle 기준 spring boot와 swagger 연동](https://linked2ev.github.io/gitlog/2020/01/05/springboot-6-API%EB%AC%B8%EC%84%9C-swagger-%EC%A0%81%EC%9A%A9/)

**Comment by kwak-bs** [comment]
감사합니다. FE쪽에서도 더 찾아볼게요!

**Comment by hataerin** [comment]
스웨거 좋은거같아요!!! 변경추척관리가 가능해서 문서화하는데 드는 시간을 아낄 수있을거같네욥ㅎㅎㅎㅎ 스웨거 사용하는거 찬성!!!!!!!!!!!
