### ISSUE TITLE
Epic 설정을 위한 구글 공유문서 제안

### ISSUE THREAD

**Issue by hataerin** [HappyNewEar/Dessert101#8]
# Epic 설정을 위한 구글 공유문서 제안

- 기능 명세를 위한 구글 공유문서를 제안합니다.

## 이슈 ❗️

- Epic단위로 명세화된 문서가 필요합니다.
  - 중요도를 색상별로 표시하였습니다.
  - 중요도 선정을 위한 회의가 필요합니다.
- 멘토에게 질문할 목록을 정리해야합니다.
![image](https://user-images.githubusercontent.com/26705587/91996959-89ac9680-ed74-11ea-842a-657f4105862f.png)

## 나의 의견 😎

- 리뷰 및 적립금 기능은 나중에 구현하는것이 좋다고 생각합니다.
- 채팅기능 관련 회의가 필요합니다.
- 관리자 페이지에서 상품 삭제보다는 숨기기기능이 좋다고 생각하는데 관련 의견 댓글 부탁드려욥

## 레퍼런스 📚

> [Epic 구글 공유 문서](https://docs.google.com/spreadsheets/d/1Hv0l3aJ4AGoIgmSDLj7El7niLNpey9udHH4gs52RGbI/edit#gid=864902051)

**Comment by kwak-bs** [comment]
역시 정리는 태린이가 최고네요! 숨기기 기능도 고민 해보면 좋을 것 같아요! 둘 다 구현해봐도 좋을 것 같구 ㅎㅋ

**Comment by Joylish** [comment]
epic, 백로그 등 스크럼 관련 단어에 대한 감을 잡을 수 있어 좋았습니다! 다들 열심히 회의에 참여해서 좋아요 ㅎㅎ
