### ISSUE TITLE
2020.09.04 새벽 MEETING 😂

### ISSUE THREAD

**Issue by JSWww** [HappyNewEar/Dessert101#9]
# 2020.09.04 새벽 MEETING

## MEETING 목적 🚩

-  유저 Epic 정리하기
-  task 우선순위 정하기

## MEETING 내용 ✍️

- 개발 스코프 설정
- 스프린트 계획 구체화
![백로그](https://user-images.githubusercontent.com/9590693/92140552-39086c80-ee4c-11ea-9dea-64467996fa74.PNG)
- 팀 로고 정함
![logo](https://user-images.githubusercontent.com/9590693/92140645-589f9500-ee4c-11ea-9d48-4180fffbb882.png)

## MEETING 결과 📌

- 프로젝트 기간동안 할 우선순위 부여함
- 유저 Epic을 Epic, 사용자 스토리 상세기능으로 세분화함

- 토요일 멘토님들께 질문할 것 정리하기
- 리액트 상태관리 라이브러리 리덕스로 결정
- 장바구니 비회원도 이용하게 할건지 고민하기
- 판매자 Epic 시간순으로 정리하기

**Comment by kwak-bs** [comment]
오늘 스프린트 계획 구체화 한 것은 잘한 것 같아요! 
마무리 까지 잘해봅시다 ㅎㅎ

**Comment by Joylish** [comment]
오늘 회의 밀리구 밀리다 약 3시간정도 하게됐는데, 다들 열심히 참여하셔서 힘든 것도 잊고 회의에 집중했던 것같아요! 오늘 회의로 epic이 어느정도 정해진 것 같은데 오늘처럼 끝까지 힘내서 하면 좋겠어요! 다들 고생하셨습니다🧚‍♀️

**Comment by hataerin** [comment]
점점 프로젝트가 구체화되는거같아서 좋았어요!! 얼른 멘토링 받구 개발 시작하구싶어요ㅎㅎㅎ 화이링링링
